#!/usr/bin/env bash
#  Bash script that loops from 1 to 10 and print some specifics strings
SCHOOL="Holberton School"
COUNT=1
while [ $COUNT -le 10 ]; do
    if [ $COUNT == 4 ]; then
	echo "bad luck"
    elif [ $COUNT == 8 ]; then
	echo "good luck"
    else
	echo "$SCHOOL"
    fi
    COUNT=$((COUNT + 1))
done
